# SPDX-FileCopyrightText: 2026 Jacques Supcik <jacques.supcik@hefr.ch>
#
# SPDX-License-Identifier: MIT

name: Docs

on:
    workflow_run:
        workflows: ["CI"]
        types: [completed]

jobs:
    build-docs:
        name: Build documentation
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.workflow_run.head_sha }}
            - name: Setup Python environment
              uses: ./.github/actions/setup-python-env
            - name: Build documentation
              run: uv run sphinx-build -M html docs public
            - name: Upload pages artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: public/html

    deploy-docs:
        needs: build-docs
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.event == 'push' &&
            startsWith(github.event.workflow_run.head_branch, 'v')
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
